name: build (jdk 17)

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Temurin 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Build
        run: ./gradlew build --stacktrace --warning-mode fail
      - name: Upload build artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/