name: publish

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Temurin 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Publish to the snapshots maven repo
        run: ./gradlew publishAllPublicationsToUkuSnapshotsRepository
        env:
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
