name: release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:17
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Publish to the maven repo
        run: ./gradlew publish
        env:
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          PUBLISH_RELEASE: owo